"""Pydantic schemas for the HR automation API."""

from __future__ import annotations

from datetime import datetime
from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field


class HRRequest(BaseModel):
    """Incoming HR request payload."""

    user_id: str
    message: str
    session_id: str | None = None


class IntentResult(BaseModel):
    """Classified intent result returned by the intent layer."""

    intent: str
    confidence: float
    entities: dict[str, Any] = Field(default_factory=dict)
    reasoning: str


class AgentResponse(BaseModel):
    """Response generated by a routed HR agent."""

    agent_name: str
    response: str
    status: Literal["success", "failed", "clarification_needed"]
    data: dict[str, Any] = Field(default_factory=dict)


class AuditEntry(BaseModel):
    """Audit log record exposed through typed application schemas."""

    model_config = ConfigDict(from_attributes=True)

    id: str
    timestamp: datetime
    user_id: str
    session_id: str | None
    raw_request: str
    classified_intent: str
    confidence_score: float
    agent_routed_to: str
    agent_response: str
    memory_context_used: bool
    processing_time_ms: int
    status: str


class MemoryContext(BaseModel):
    """Memory context assembled from short-term and long-term memory."""

    stm_entries: list[Any] = Field(default_factory=list)
    ltm_entries: list[Any] = Field(default_factory=list)


class ProcessResponse(BaseModel):
    """Final response payload for processed HR requests."""

    request_id: str
    intent: IntentResult
    response: AgentResponse
    processing_time_ms: int
